[2025-04-06T14:17:18.321+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T14:17:18.731+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_quality.check_transaction_id_quality manual__2025-04-06T14:16:54.660033+00:00 [queued]>
[2025-04-06T14:17:18.750+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_quality.check_transaction_id_quality manual__2025-04-06T14:16:54.660033+00:00 [queued]>
[2025-04-06T14:17:18.752+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-06T14:17:18.793+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): check_transaction_id_quality> on 2025-04-06 14:16:54.660033+00:00
[2025-04-06T14:17:18.844+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1328) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T14:17:18.848+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_data_quality', 'check_transaction_id_quality', 'manual__2025-04-06T14:16:54.660033+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_quality.py', '--cfg-path', '/tmp/tmp35bit005']
[2025-04-06T14:17:18.851+0000] {standard_task_runner.py:72} INFO - Started process 1338 to run task
[2025-04-06T14:17:18.852+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask check_transaction_id_quality
[2025-04-06T14:17:19.330+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_data_quality.check_transaction_id_quality manual__2025-04-06T14:16:54.660033+00:00 [running]> on host 2e277e0df613
[2025-04-06T14:17:20.113+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laurenziusjulioanreaja@mail.ugm.ac.id,selvianisacahyamukti@mail.ugm.ac.id,yudypratamafanggidae@mail.ugm.ac.id' AIRFLOW_CTX_DAG_OWNER='julio' AIRFLOW_CTX_DAG_ID='dag_data_quality' AIRFLOW_CTX_TASK_ID='check_transaction_id_quality' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T14:16:54.660033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T14:16:54.660033+00:00'
[2025-04-06T14:17:20.142+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T14:17:20.143+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T14:17:20.145+0000] {logging_mixin.py:190} INFO - Current task name:check_transaction_id_quality state:running start_date:2025-04-06 14:17:18.732817+00:00
[2025-04-06T14:17:20.146+0000] {logging_mixin.py:190} INFO - Dag name:dag_data_quality and current dag run status:running
[2025-04-06T14:17:20.147+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T14:17:20.511+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_data_quality.py", line 36, in check_transaction_id_quality
    conn = duckdb.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1337). See also https://duckdb.org/docs/connect/concurrency
[2025-04-06T14:17:20.685+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T14:17:20.687+0000] {logging_mixin.py:190} INFO - Task start:2025-04-06 14:17:18.732817+00:00 end:2025-04-06 14:17:20.682110+00:00 duration:1.949293
[2025-04-06T14:17:20.688+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): check_transaction_id_quality> dag:<DAG: dag_data_quality> dagrun:<DagRun dag_data_quality @ 2025-04-06 14:16:54.660033+00:00: manual__2025-04-06T14:16:54.660033+00:00, state:running, queued_at: 2025-04-06 14:16:54.837661+00:00. externally triggered: True>
[2025-04-06T14:17:20.689+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1337). See also https://duckdb.org/docs/connect/concurrency
[2025-04-06T14:17:20.690+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_quality, task_id=check_transaction_id_quality, run_id=manual__2025-04-06T14:16:54.660033+00:00, execution_date=20250406T141654, start_date=20250406T141718, end_date=20250406T141720
[2025-04-06T14:17:21.294+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T14:17:21.296+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 52 for task check_transaction_id_quality (IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1337). See also https://duckdb.org/docs/connect/concurrency; 1338)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_data_quality.py", line 36, in check_transaction_id_quality
    conn = duckdb.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1337). See also https://duckdb.org/docs/connect/concurrency
[2025-04-06T14:17:21.369+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T14:17:21.393+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
