[2025-04-06T13:05:27.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T13:05:27.061+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_duckdb_dag_custom_class.fail_test manual__2025-04-06T12:59:39.102741+00:00 [queued]>
[2025-04-06T13:05:27.072+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_duckdb_dag_custom_class.fail_test manual__2025-04-06T12:59:39.102741+00:00 [queued]>
[2025-04-06T13:05:27.072+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-06T13:05:27.089+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): fail_test> on 2025-04-06 12:59:39.102741+00:00
[2025-04-06T13:05:27.099+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=342) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T13:05:27.101+0000] {standard_task_runner.py:72} INFO - Started process 344 to run task
[2025-04-06T13:05:27.101+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_duckdb_dag_custom_class', 'fail_test', 'manual__2025-04-06T12:59:39.102741+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/etl_duckdb_dag.py', '--cfg-path', '/tmp/tmp6f6v1vjw']
[2025-04-06T13:05:27.102+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask fail_test
[2025-04-06T13:05:27.148+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_duckdb_dag_custom_class.fail_test manual__2025-04-06T12:59:39.102741+00:00 [running]> on host 2e277e0df613
[2025-04-06T13:05:27.256+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laurenziusjulioanreaja@mail.ugm.ac.id,selvianisacahyamukti@mail.ugm.ac.id,yudypratamafanggidae@mail.ugm.ac.id' AIRFLOW_CTX_DAG_OWNER='julio' AIRFLOW_CTX_DAG_ID='etl_duckdb_dag_custom_class' AIRFLOW_CTX_TASK_ID='fail_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T12:59:39.102741+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T12:59:39.102741+00:00'
[2025-04-06T13:05:27.258+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T13:05:27.258+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T13:05:27.259+0000] {logging_mixin.py:190} INFO - Current task name:fail_test state:running start_date:2025-04-06 13:05:27.062357+00:00
[2025-04-06T13:05:27.259+0000] {logging_mixin.py:190} INFO - Dag name:etl_duckdb_dag_custom_class and current dag run status:running
[2025-04-06T13:05:27.260+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T13:05:27.261+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_duckdb_dag.py", line 36, in fail_test
    raise Exception("ðŸ’¥ Simulasi error: email notifikasi akan dikirim!")
Exception: ðŸ’¥ Simulasi error: email notifikasi akan dikirim!
[2025-04-06T13:05:27.275+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T13:05:27.276+0000] {logging_mixin.py:190} INFO - Task start:2025-04-06 13:05:27.062357+00:00 end:2025-04-06 13:05:27.275392+00:00 duration:0.213035
[2025-04-06T13:05:27.277+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): fail_test> dag:<DAG: etl_duckdb_dag_custom_class> dagrun:<DagRun etl_duckdb_dag_custom_class @ 2025-04-06 12:59:39.102741+00:00: manual__2025-04-06T12:59:39.102741+00:00, state:running, queued_at: 2025-04-06 12:59:39.170447+00:00. externally triggered: True>
[2025-04-06T13:05:27.277+0000] {logging_mixin.py:190} INFO - Failure caused by ðŸ’¥ Simulasi error: email notifikasi akan dikirim!
[2025-04-06T13:05:27.278+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_duckdb_dag_custom_class, task_id=fail_test, run_id=manual__2025-04-06T12:59:39.102741+00:00, execution_date=20250406T125939, start_date=20250406T130527, end_date=20250406T130527
[2025-04-06T13:05:27.302+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-04-06T13:05:27.303+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-04-06T13:05:28.979+0000] {email.py:283} INFO - Sent an alert email to ['laurenziusjulioanreaja@mail.ugm.ac.id', 'selvianisacahyamukti@mail.ugm.ac.id', 'yudypratamafanggidae@mail.ugm.ac.id']
[2025-04-06T13:05:31.056+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T13:05:31.057+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task fail_test (ðŸ’¥ Simulasi error: email notifikasi akan dikirim!; 344)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_duckdb_dag.py", line 36, in fail_test
    raise Exception("ðŸ’¥ Simulasi error: email notifikasi akan dikirim!")
Exception: ðŸ’¥ Simulasi error: email notifikasi akan dikirim!
[2025-04-06T13:05:31.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T13:05:31.114+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-06T13:05:31.117+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
