[2025-04-06T14:23:45.895+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T14:23:46.104+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_quality.record_quality_log scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T14:23:46.130+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_quality.record_quality_log scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-04-06T14:23:46.136+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-06T14:23:46.179+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): record_quality_log> on 2025-04-05 00:00:00+00:00
[2025-04-06T14:23:46.194+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1509) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T14:23:46.196+0000] {standard_task_runner.py:72} INFO - Started process 1528 to run task
[2025-04-06T14:23:46.197+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_data_quality', 'record_quality_log', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_quality.py', '--cfg-path', '/tmp/tmpyq224vqf']
[2025-04-06T14:23:46.201+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask record_quality_log
[2025-04-06T14:23:46.287+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_data_quality.record_quality_log scheduled__2025-04-05T00:00:00+00:00 [running]> on host 2e277e0df613
[2025-04-06T14:23:46.439+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laurenziusjulioanreaja@mail.ugm.ac.id,selvianisacahyamukti@mail.ugm.ac.id,yudypratamafanggidae@mail.ugm.ac.id' AIRFLOW_CTX_DAG_OWNER='julio' AIRFLOW_CTX_DAG_ID='dag_data_quality' AIRFLOW_CTX_TASK_ID='record_quality_log' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-04-06T14:23:46.441+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T14:23:46.442+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T14:23:46.442+0000] {logging_mixin.py:190} INFO - Current task name:record_quality_log state:running start_date:2025-04-06 14:23:46.106514+00:00
[2025-04-06T14:23:46.443+0000] {logging_mixin.py:190} INFO - Dag name:dag_data_quality and current dag run status:running
[2025-04-06T14:23:46.444+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T14:23:46.462+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_data_quality.py", line 76, in record_quality_log
    conn = duckdb.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1511). See also https://duckdb.org/docs/connect/concurrency
[2025-04-06T14:23:46.480+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T14:23:46.481+0000] {logging_mixin.py:190} INFO - Task start:2025-04-06 14:23:46.106514+00:00 end:2025-04-06 14:23:46.479555+00:00 duration:0.373041
[2025-04-06T14:23:46.481+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): record_quality_log> dag:<DAG: dag_data_quality> dagrun:<DagRun dag_data_quality @ 2025-04-05 00:00:00+00:00: scheduled__2025-04-05T00:00:00+00:00, state:running, queued_at: 2025-04-06 14:16:54.961824+00:00. externally triggered: False>
[2025-04-06T14:23:46.482+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1511). See also https://duckdb.org/docs/connect/concurrency
[2025-04-06T14:23:46.483+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=dag_data_quality, task_id=record_quality_log, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250406T142346, end_date=20250406T142346
[2025-04-06T14:23:46.503+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-04-06T14:23:46.504+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-04-06T14:23:47.994+0000] {email.py:283} INFO - Sent an alert email to ['laurenziusjulioanreaja@mail.ugm.ac.id', 'selvianisacahyamukti@mail.ugm.ac.id', 'yudypratamafanggidae@mail.ugm.ac.id']
[2025-04-06T14:23:50.832+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T14:23:50.833+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 62 for task record_quality_log (IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1511). See also https://duckdb.org/docs/connect/concurrency; 1528)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_data_quality.py", line 76, in record_quality_log
    conn = duckdb.connect(DB_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 1511). See also https://duckdb.org/docs/connect/concurrency
[2025-04-06T14:23:50.872+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T14:23:50.913+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-06T14:23:50.919+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
