[2025-04-06T14:36:04.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-06T14:36:04.682+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_quality.record_quality_log manual__2025-04-06T14:29:46.981721+00:00 [queued]>
[2025-04-06T14:36:04.702+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_quality.record_quality_log manual__2025-04-06T14:29:46.981721+00:00 [queued]>
[2025-04-06T14:36:04.705+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-06T14:36:04.732+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): record_quality_log> on 2025-04-06 14:29:46.981721+00:00
[2025-04-06T14:36:04.747+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1772) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-06T14:36:04.749+0000] {standard_task_runner.py:72} INFO - Started process 1774 to run task
[2025-04-06T14:36:04.750+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_data_quality', 'record_quality_log', 'manual__2025-04-06T14:29:46.981721+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_data_quality.py', '--cfg-path', '/tmp/tmpach6hpl6']
[2025-04-06T14:36:04.753+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask record_quality_log
[2025-04-06T14:36:04.817+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_data_quality.record_quality_log manual__2025-04-06T14:29:46.981721+00:00 [running]> on host 2e277e0df613
[2025-04-06T14:36:04.928+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laurenziusjulioanreaja@mail.ugm.ac.id,selvianisacahyamukti@mail.ugm.ac.id,yudypratamafanggidae@mail.ugm.ac.id' AIRFLOW_CTX_DAG_OWNER='julio' AIRFLOW_CTX_DAG_ID='dag_data_quality' AIRFLOW_CTX_TASK_ID='record_quality_log' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T14:29:46.981721+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T14:29:46.981721+00:00'
[2025-04-06T14:36:04.929+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-06T14:36:04.930+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-06T14:36:04.930+0000] {logging_mixin.py:190} INFO - Current task name:record_quality_log state:running start_date:2025-04-06 14:36:04.683600+00:00
[2025-04-06T14:36:04.931+0000] {logging_mixin.py:190} INFO - Dag name:dag_data_quality and current dag run status:running
[2025-04-06T14:36:04.931+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-06T14:36:04.969+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_data_quality.py", line 93, in record_quality_log
    status = "success" if "✅" in tid_check_msg and "✅" in null_check_msg else "failed"
                          ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[2025-04-06T14:36:04.985+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-06T14:36:04.986+0000] {logging_mixin.py:190} INFO - Task start:2025-04-06 14:36:04.683600+00:00 end:2025-04-06 14:36:04.984541+00:00 duration:0.300941
[2025-04-06T14:36:04.986+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): record_quality_log> dag:<DAG: dag_data_quality> dagrun:<DagRun dag_data_quality @ 2025-04-06 14:29:46.981721+00:00: manual__2025-04-06T14:29:46.981721+00:00, state:running, queued_at: 2025-04-06 14:29:47.145690+00:00. externally triggered: True>
[2025-04-06T14:36:04.987+0000] {logging_mixin.py:190} INFO - Failure caused by argument of type 'NoneType' is not iterable
[2025-04-06T14:36:04.988+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=dag_data_quality, task_id=record_quality_log, run_id=manual__2025-04-06T14:29:46.981721+00:00, execution_date=20250406T142946, start_date=20250406T143604, end_date=20250406T143604
[2025-04-06T14:36:05.005+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:155: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-04-06T14:36:05.006+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-04-06T14:36:06.564+0000] {email.py:283} INFO - Sent an alert email to ['laurenziusjulioanreaja@mail.ugm.ac.id', 'selvianisacahyamukti@mail.ugm.ac.id', 'yudypratamafanggidae@mail.ugm.ac.id']
[2025-04-06T14:36:08.872+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-06T14:36:08.873+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task record_quality_log (argument of type 'NoneType' is not iterable; 1774)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_data_quality.py", line 93, in record_quality_log
    status = "success" if "✅" in tid_check_msg and "✅" in null_check_msg else "failed"
                          ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[2025-04-06T14:36:08.900+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-06T14:36:08.953+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-06T14:36:08.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
