[2025-04-17T23:01:43.531+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T23:01:43.573+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_duckdb_dag_custom_class.extract scheduled__2025-04-16T00:00:00+00:00 [queued]>
[2025-04-17T23:01:43.596+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_duckdb_dag_custom_class.extract scheduled__2025-04-16T00:00:00+00:00 [queued]>
[2025-04-17T23:01:43.597+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-17T23:01:43.632+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-04-16 00:00:00+00:00
[2025-04-17T23:01:43.653+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=12104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-17T23:01:43.656+0000] {standard_task_runner.py:72} INFO - Started process 12115 to run task
[2025-04-17T23:01:43.656+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_duckdb_dag_custom_class', 'extract', 'scheduled__2025-04-16T00:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/etl_duckdb_dag.py', '--cfg-path', '/tmp/tmp0i3s__33']
[2025-04-17T23:01:43.658+0000] {standard_task_runner.py:105} INFO - Job 187: Subtask extract
[2025-04-17T23:01:43.778+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_duckdb_dag_custom_class.extract scheduled__2025-04-16T00:00:00+00:00 [running]> on host 697c9a4320f6
[2025-04-17T23:01:43.990+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='laurenziusjulioanreaja@mail.ugm.ac.id,selvianisacahyamukti@mail.ugm.ac.id,yudypratamafanggidae@mail.ugm.ac.id' AIRFLOW_CTX_DAG_OWNER='julio' AIRFLOW_CTX_DAG_ID='etl_duckdb_dag_custom_class' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-16T00:00:00+00:00'
[2025-04-17T23:01:43.993+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-17T23:01:43.994+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-17T23:01:43.995+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-04-17 23:01:43.575047+00:00
[2025-04-17T23:01:43.996+0000] {logging_mixin.py:190} INFO - Dag name:etl_duckdb_dag_custom_class and current dag run status:running
[2025-04-17T23:01:43.996+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-17T23:01:44.023+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_duckdb_dag.py", line 46, in extract
    pipeline = ETLPipeline(DB_PATH, GDRIVE_LINK, DATA_PATH)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 12, in __init__
    self.conn = duckdb.connect(database=self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 12114). See also https://duckdb.org/docs/connect/concurrency
[2025-04-17T23:01:44.077+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-17T23:01:44.078+0000] {logging_mixin.py:190} INFO - Task start:2025-04-17 23:01:43.575047+00:00 end:2025-04-17 23:01:44.076077+00:00 duration:0.50103
[2025-04-17T23:01:44.079+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): extract> dag:<DAG: etl_duckdb_dag_custom_class> dagrun:<DagRun etl_duckdb_dag_custom_class @ 2025-04-16 00:00:00+00:00: scheduled__2025-04-16T00:00:00+00:00, state:running, queued_at: 2025-04-17 23:00:51.156788+00:00. externally triggered: False>
[2025-04-17T23:01:44.080+0000] {logging_mixin.py:190} INFO - Failure caused by IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 12114). See also https://duckdb.org/docs/connect/concurrency
[2025-04-17T23:01:44.080+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_duckdb_dag_custom_class, task_id=extract, run_id=scheduled__2025-04-16T00:00:00+00:00, execution_date=20250416T000000, start_date=20250417T230143, end_date=20250417T230144
[2025-04-17T23:01:44.143+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-17T23:01:44.144+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 187 for task extract (IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 12114). See also https://duckdb.org/docs/connect/concurrency; 12115)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_duckdb_dag.py", line 46, in extract
    pipeline = ETLPipeline(DB_PATH, GDRIVE_LINK, DATA_PATH)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 12, in __init__
    self.conn = duckdb.connect(database=self.db_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/opt/***/dags/database.duckdb": Conflicting lock is held in /usr/local/bin/python3.12 (PID 12114). See also https://duckdb.org/docs/connect/concurrency
[2025-04-17T23:01:44.192+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-17T23:01:44.248+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T23:01:44.251+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
